// <auto-generated />
namespace Tarefa3_MVC.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.4.4")]
    public sealed partial class Curso_Sobrenome : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(Curso_Sobrenome));
        
        string IMigrationMetadata.Id
        {
            get { return "202103051300490_Curso_Sobrenome"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
